name: model
description: A simple command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  json_annotation: ^4.3.0

dependencies:
  json_annotation: ^4.3.0
  drift: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0